### ISSUE TITLE
Cut off text when editing your bio page

### ISSUE THREAD

**Issue by ssyasoni** [momentum-mod/website#118]
When entering content into the user's bio, it will allow you to save changes even though the length will get cut off soon after saving. It should grey out the save changes when the text is at max length. This will become confusing to how much text can be entered into the user's bio.

For example,

Here is the content saved (and allowed to be saved).
![bio](https://user-images.githubusercontent.com/22774582/48972147-c28dd800-eff2-11e8-81a5-175cc7976fc0.PNG)

Then the content gets cut off after saved (like in this photo):
![autocutoff](https://user-images.githubusercontent.com/22774582/48972149-c4f03200-eff2-11e8-9515-4c1db989db06.PNG)

When testing out more text it does grey out "save changes" when more text was entered in.
![savechanges](https://user-images.githubusercontent.com/22774582/48972150-c6b9f580-eff2-11e8-8028-89107ccc90bd.PNG)

**Comment by ssyasoni** [comment]
Tested on http://141.210.25.113/ as well, error is given as shown below:

![bioerror](https://user-images.githubusercontent.com/22774582/48972290-43e66a00-eff5-11e8-82ba-717aaeef5286.PNG)

**Comment by lubna9** [comment]
This is not a n issue anymore because i tested it and if the text exceeds 500 characters, the user is informed and isnt allowed to save changes. 
Closing Issue.
