### ISSUE TITLE
Map edit form needs implemented

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#150]
During the "pending/testing" periods:
 * Allow updating the map file
 * Allow updating the map name
 * Allow updating map bio
 * Allow update map images (during testing->ready for release only)

During "Approved" status:
 * Allow updating the bio (at any time for the authors of the map)
 * Allow adding more people to credits, but...
 * ... Only admins can remove people from credits

**Comment by tsa96** [comment]
Something I've noticed - it's possible add credits for the same user in multiple places. Worth doing checks for this on backend for sure (including e2e tests), plus frontend I supposed - easy thing to test after you leave the credits page

**Comment by tsa96** [comment]
Oh I did this lol
