### ISSUE TITLE
Add Patreon/Ko-Fi social link to user profiles

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#197]
https://docs.patreon.com/#oauth
https://www.npmjs.com/package/passport-patreon

**Comment by tsa96** [comment]
Users shouldn't need to use OAuth to prove it's them, why would it matter if they linked someone else's Patreon/Ko-Fi account? This can just be a string entry in the Profile table.

Do we care about restricting this to only verified mappers? Probably doesn't really matter in non-mappers use it on their profile (why would anyone donate to them??) but maybe it's nice to make it explicitly only a mapper thing. If so, we to figure out what's going on with the `MAPPER` role anyway, I don't really understand what the point of it will be after map submission is added (which presumably any user can do - if not, more work for mods and potentially discouraging for new mappers).

**Comment by tsa96** [comment]
Consolidating into https://github.com/momentum-mod/website/issues/766
