### ISSUE TITLE
Map ratings/feedback

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#203]
Allow users that beat the map to submit feedback directly to the mapper. They can get a one-time cosmetic XP gain or something from doing it each time. It should be emphasized that reviews aren't public, only map authors and mods/admins can see them.

**Comment by tsa96** [comment]
Ratings we don't want, we just have favourites system and soon map playtime stats. Feedback we absolutely will have for map submission/testing, that'll fall into that.
