### ISSUE TITLE
Admin/mod action log

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#218]
Make a page to show mod/admin actions with timestamps

**Comment by tsa96** [comment]
1. Admins can see admin and mod actions, mods can see mod actions. I'm not sure we have any events that where we want to restrict mods from seeing admin actions, but it seems good to do in principle anyway.
2. Yes, this is the hardest thing. Storing something like what map details an admin changes makes sense, it just means we have to store some arbitrary JSON.
    1. Yes, that's a slight security concern however (1) all the update data is validated always and (2) only admins/mods can use it.
    2. So, let's just store the difference between the two objects. Performance doesn't matter here, just grab the models from DB with Prisma before and after the change is applied, and filter out any matching keys/values. _Note, as per https://github.com/momentum-mod/website/issues/747 I've been wanting to do a small library of helper functions for this, rather than use Lodash or whatever. So doing a library package called `libs/utils` for this makes sense, if nobody has started in by that already._
3. Not quite sure what you mean, it should just bit a list in the admin section of frontend showing everything, ideally with some search functionality using query params.

To flesh out the types database structure a bit more, I think we'll want:
1. An enum for all possible `AdminActivityType` _(note, we use the Prisma schema for this now actually, that's a refactor I'm currently working on - I'll have submitted in next couple days, but hmu in Discord to talk about this)_
2. A new model/table
```prisma
model AdminActivities {
  id Int @id @default(autoincrement())

  comment String? // Update any admin endpoints where it makes sense to take a `comment` property e.g. why a user was banned
  type AdminActivityType
  target Bigint @db.BigInt // where `target` is an index into _some_ table set by the value of `type`
  data Json // Diff of before and after


  // this will need corresponding relation on User 
  user   User @relation(fields: [userID], references: [id], onDelete: Cascade)
  userID Int

  createdAt DateTime @default(now()) (no updatedat)
}
```
Typing the `data` seems near-impossible, so let's leave it untyped and just format it nicely on the frontend.

I recognise this is a bit of a loose spec but happy to clarify/discuss anything in future. Also, as a rule of thumb, these changes _only_ affect stuff from the `/admin` endpoints. I know there's https://github.com/momentum-mod/website/issues/743 open at the moment but we really shouldn't merge the admin versions of endpoints with regular ones, if there's dupe code just split stuff in the other services up a bit so the AdminService can call them. So generally we can think of this issue and just working in AdminService land and beefing that stuff up, not touching the rest of the API.

**Comment by tsa96** [comment]
https://github.com/momentum-mod/website/pull/915 concludes this, great work Gordi!
