### ISSUE TITLE
Add loading indicator for components

### ISSUE THREAD

**Issue by Corey28** [momentum-mod/website#233]
Some sort of image/element for client components waiting for things like server requests

**Comment by tsa96** [comment]
[NbSpinnerModule](https://akveo.github.io/nebular/docs/components/spinner)

**Comment by tsa96** [comment]
Ended up liking NbSpinnerModule, and wrote my own simplified version when removing Nebular recently: https://github.com/momentum-mod/website/blob/main/apps/frontend/src/app/directives/spinner.directive.ts. So this is done, `[mSpinner]='foo'` will show a spinner over a component for some boolean `foo` whenever true.
