### ISSUE TITLE
Make sure pipe(finalize ... ) is used in all HTTP requests where applicable

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#244]
It can be used to set a `didRequest` or similar boolean to show if there aren't any results for things. Also make sure it's used instead of the `complete` function of an HTTP observable, as they aren't always called (especially when there's an error)!

**Comment by tsa96** [comment]
[Here's a good explanation](https://stackoverflow.com/a/60466443) of how Angular's HTTP client handles `next`s and `complete`s - tl;dr it fires them both at the same time. So it really doesn't matter if you perform any logic in a `finalize` operator or in the `next` block of a subscription. But the former relies on knowing that quite obscure fact about Angular HTTP, so IMO it's far better to use the latter.
