### ISSUE TITLE
Add API versioning to API route

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#246]
E.g. `/api/v1/<endpoint>`

Even though we're still in v1 with no major version changes planned soon, it's still good to do it ASAP just in case.

**Comment by tsa96** [comment]
This is in place, but just on the front of each controller declaration at the moment which is silly. I'll move it out to the config soon.

@Gocnak how are we going to handle updating this convar ingame? We don't have a way of updating a convar when a default changes, do we?

**Comment by Gocnak** [comment]
Can probably move it over to using an override enabler cvar which then uses the cvar for the domain. People won't really be changing the base URL unless they're working on the site.

**Comment by tsa96** [comment]
Oh, this is finished. We use `v1` as a default and add specific versions for everything else (currently nothing).

My game branch has some basic version handling atm but it's ugly because I hate C++ macros - we can discuss that in red.
