### ISSUE TITLE
Frontend End-to-End Tests

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#261]

**Comment by tsa96** [comment]
Really a constantly ongoing issue, there's tons of E2E tests we could write but not sure when we'll get round to them.

Let's try to prioritize parts of the frontend with more complex components - writing E2E tests is really easy, if a lot of stuff gets interacted with, that's just more actions to write.

So we should definitely do map submission, this is by far the most complex part of the frontend currently. We're gonna work on that really soon, so by doing E2E tests there we'll make an excellent example for how to write other ones.

**Comment by tsa96** [comment]
With the current amount of development, I don't consider widespread frontend E2E coverage to be remotely feasible. The Cypress setup is in place, people are welcome to write them, but it should never be a requirement for anything on the dashboard. If there's ever cases where we really need it, we could make an issue for that specifically, but I don't think an issue this general is worth keeping open - @Gocnak do you agree?
