### ISSUE TITLE
Be able to filter uploaded maps

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#265]
Add filter controls inside of the map upload status to easily filter results by name, status, etc

**Comment by vindow** [comment]
A few questions on implementation:

1. Currently other filter options for other components look something like this:
![1](https://user-images.githubusercontent.com/5974776/105564902-11ba1b00-5cd9-11eb-9a7d-b1c12fa24c87.png)
![4](https://user-images.githubusercontent.com/5974776/105564904-1383de80-5cd9-11eb-96d9-518806c9ca35.png)
While the map filtering/search looks like this:
![2](https://user-images.githubusercontent.com/5974776/105564769-7de84f00-5cd8-11eb-954a-6bb4e7beb709.png)
Which works great for search but won't look right with a filter. I threw something quick together to look like this:
![3](https://user-images.githubusercontent.com/5974776/105564796-97899680-5cd8-11eb-82e9-4f4942a57d94.png)
I was wondering if I should replace the old search with this look without the status selector for the other map pages (browse, favorites, library) or if I should preserve the look of the original for the other map pages.
2. Should I hide the new filter menu behind a button like the other filter options or just keep them always shown as default?
3. Besides name and status are there any other filter categories I should add?
4. Should I use the status names [from here?](https://github.com/momentum-mod/website/blob/staging/client/src/app/%40core/models/map-upload-status.model.ts) The map list component itself seems to use them but the underscores for multi-word statuses might be unwanted for the front-end.

**Comment by Gocnak** [comment]
1. So for the uploaded maps section, the map's status and name is probably the most two important filters. Though, if all the map browsing components just reused the same search component that toggled things off depending on the list (public, in-library, in-favorites, uploaded) then that would work splendidly.
2. They can be shown by default for now.
3. Gamemode might be pretty important for people to find specific maps for modes. Searching by author would be another in the future to consider.
4. Yeah they would need to tie to english versions. Try checking the "Notification" pop-up dialog thing (following a user/map), it does the mapping to actual english string there that you can do.
