### ISSUE TITLE
Consider adding User and Run comments

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#273]
Comments can be made for Users and Runs.
Comments can only be created if the given user making the comment has a certain cosmetic XP level (10+ maybe?).
Comments can be edited only by their creator.
Comments can be thumbs-upped by others (also only if level 10+).
Comments can be reported for spam/bad content.

**Comment by tsa96** [comment]
We should sit down and discuss this. A comment system could definitely make sense, maybe for maps as well, but idk how much purpose it really serves. Some quick thoughts:
- Only worth doing run comments if hooked up ingame - rare that people ever look at individual run pages on the site
- Run comments could have a youtube timestamp-like system
- Map comments sound like they'd work best as part of some kinda review system, with afaik we don't intend to do (besides showing total favorites)
- User comments have the potential to just be really dumb. Steam kinda has this problem already - so many comments are just spam. Do we really expect to get much out of it ourselves?

**Comment by tsa96** [comment]
The use-cases for this feel too vague for actionable work, so closing until 1.0.0. If social stuff feels lacking after 1.0.0 we could reconsider, but lets wait and see what people are actually asking for.

**Comment by Gocnak** [comment]
User comments = steam profile comments
Run comments = likely for WRs only, which will have YouTube uploads
Only use case would be Map comments mainly, but this can move to something like Discord or Steam forums where moderation already exists + is hosted for us
