### ISSUE TITLE
Allow user account deletion

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#292]
In accordance with GDPR, we must be able to comply with the right to be forgotten.

SteamIDs are the only automatically collected user-identification, other than the data explicitly set by the end user on the site. Allowing users to delete their account, and all related data with it.

**Comment by tsa96** [comment]
Several possible approaches
Create new role `DELETED`, assign to that user, remove all their info, rename to "Deleted User"
Pros: 
- Minimal DB operations
- Easy to do
Cons:
- Potentially lots of deleted users sitting in DB
- Extra role to handling in some places

Alternative: use placeholders
Rather than new role, just change them to placeholder and remove everything
Cons:
- You lose uniqueness of placeholder aliases
  - Unless we merge users together, but that breaks constraint of one user having one ranked run per track per submode per map
- Placeholders now have runs on leaderboard??

Do we want to just allow runs also be deleted? That way we could actually delete users, or make them a placeholder if they have any maps submitted. Gives even more privacy but I can't imagine us having any kind of legal obligation. New ranking system could probably handle it fine though.

My preference is just towards top method (new `DELETED` role)

@Gocnak thoughts?

**Comment by tsa96** [comment]
Just realised that admins can delete users already. Prisma schema is configured to `onDelete: SetNull` for _runs_, but `Cascade` for _ranks_. Which doesn't really make sense - we don't recalculate all the `rank` fields on the `Rank` table, we could have a leaderboard that's just missing a rank. This is likely to mess with pagination, really not something we want.

So how about we do the same approach (with `DELETED` role) as above, in `users.service.ts` and have both the `/user` and `/admin` endpoints use that same logic?

**Comment by Gocnak** [comment]
Deleted role sounds good 👍

**Comment by tsa96** [comment]
Okay great!

Here's a basic `BadgeDeleted.svg` for the frontend.
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="64" height="64">
  <defs>
    <linearGradient id="a">
      <stop offset="0" style="stop-color:#ffb446;stop-opacity:1"/>
      <stop offset="1" style="stop-color:#ffec3c;stop-opacity:1"/>
    </linearGradient>
    <linearGradient xlink:href="#a" id="b" x1="151.199" x2="151.199" y1="235.476" y2="3.93" gradientTransform="matrix(.2764 0 0 .2764 -2.782 -1.086)" gradientUnits="userSpaceOnUse"/>
  </defs>
  <path d="M.05 57.196C.05 60.513 3.464 64 6.78 64l35.342-35.336 9.124 8.977c1.66 0 12.704-11.05 12.704-12.708l-8.981-9.118.73-.762c0-3.04-3.737-6.81-6.777-6.81l-.82.76L39.009 0c-1.657 0-12.696 11.058-12.696 12.717l8.973 9.125z" style="fill:url(#b);fill-opacity:1;stroke:none;stroke-width:.104467;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"/>
</svg>
```

@GordiNoki you want to take this then? I can do the frontend if needed, we'll need:
- Checking for cases where we're doing `PLACEHOLDER` role checks - we filter them out of some lists and things iirc - should do in this case as well
- Adding above badge
- Adding a button to the profile-edit page that spawns a **very** scary looking popup warning that account deletion is permanent. Anyone who deletes their account will be unable to play on that Steam account again.

Though on that, honestly, I'm a little worried that this will cause one or two idiots to come crying to us by mistake. Plus, we need to handle the case of someone deleting this account, then signing in again through that same account. Honestly, I think in this case all we need to do to be GDPR compliant, is unsure that on requesting deletion we delete everything identifiable, then if they auth again, in the `users.service` `findOrCreateFromWeb`, just removed the `DELETED` role and repopulate their info with the info we just got from Steam.

**Comment by GordiNoki** [comment]
Sorry for late answer. Yea, I think I can make account deletion. About account recovery, what should we store to identify user then?

**Comment by tsa96** [comment]
Sorry, wrong badge, here's correct one
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="64" height="64">
	<linearGradient id="a" x1="9.469" x2="54.516" y1="19.002" y2="45.01" gradientUnits="userSpaceOnUse">
		<stop offset="0" style="stop-color:#996425"/>
		<stop offset="1" style="stop-color:#7f3800"/>
	</linearGradient>
	<path d="M32 6C17.6 6 6 17.6 6 32s11.6 26 26 26 26-11.6 26-26S46.3 6 32 6M18.4 23.7l2.8-2.8 2.8 2.8 2.8-2.8 2.8 2.8-2.8 2.8 2.8 2.8-3 2.7-2.8-2.8-2.7 2.8-2.8-2.8 2.8-2.8-2.7-2.7m.3 22.6c2.1-5.3 7.2-9.1 13.3-9.1s11.2 3.8 13.3 9.1H18.7m26.9-17.1L42.9 32l-2.8-2.8-2.7 2.8-2.8-2.8 2.8-2.8-2.8-2.8 2.8-2.8 2.8 2.8 2.8-2.8 2.8 2.8-2.8 2.8 2.6 2.8z" style="fill:url(#a)"/>
</svg>
```
