### ISSUE TITLE
Merge server/models/db and server/models using new class-based Sequelize models

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#308]
As found in [model definition](http://docs.sequelizejs.com/manual/models-definition.html), models are supposed to be classes that extend the Sequelize Model class, and call `<ModelName>.init({}. {sequelize});` to actually init.

This means the models we have outside of the db folder can merge with those inside, as those methods can go inside of the model class itself, and all we do is export the model's class, instead of all the functions.

**Comment by TheRealHona** [comment]
Added `Rewrite: Initial` tag since this would become redundant
