### ISSUE TITLE
Consider adding client error report generation and submission

### ISSUE THREAD

**Issue by Corey28** [momentum-mod/website#332]
Creating a web server endpoint (or endpoints) to accept error reports generated and sent from the web client (and possibly game client) could be useful for debugging purposes. Angular provides a really nice way to catch uncaught errors globally, and [here](https://blog.angularindepth.com/expecting-the-unexpected-best-practices-for-error-handling-in-angular-21c3662ef9e4) is a great resource on how to utilize global error catching. A notification of some kind could also be generated on error report submission.

**Comment by tsa96** [comment]
https://github.com/momentum-mod/website/issues/620 trumps this
