### ISSUE TITLE
Smooth scrollbars

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/website#337]
https://idiotwu.github.io/smooth-scrollbar/

Suggested by Nem

**Comment by Flipybitz** [comment]
This can be done with 'scroll-behavior: smooth' in most modern browsers.

**Comment by MantasAD** [comment]
If `scroll-behavior: smooth` matches the desired behavior, then this issue can be closed because I have already added it. https://github.com/momentum-mod/website/blob/staging/client/src/app/%40theme/styles/styles.scss#L42

**Comment by tsa96** [comment]
scroll-behavior: smooth; is a desirable property as it causes smooth scrolling between divs when the nav menu items are triggered, however it doesn't affect the scrollbar or scrolling with the scroll wheel: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

The smooth-scrollbar npm plugin would be easy to add, though it's debatable whether it's worth including a ~50kb js file just to slightly smooth out scrolling.

**Comment by Gocnak** [comment]
Not worth it, that demo site is absolutely awful to scroll on in mobile browsers.

**Comment by tsa96** [comment]
Issue closed just by me whining a bit! I'm invaluable
