### ISSUE TITLE
Reject runs with strafe/jump/stats counts > the total amount of ticks

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#340]
Currently we do not reject runs for getting unrealistic statistics, leading to...

![image](https://user-images.githubusercontent.com/5162166/60400601-037b3b80-9b44-11e9-8612-ac7e1865ff9e.png)

Yeah... At the very minimum, reject runs that have blatantly wrong statistics.

**Comment by Gelmo** [comment]
I would suggest asking Zpamm (Zpamm#1739) from the CSGO KZ community (https://discord.gg/VaG9tM) about similar implementations in GlobalAPI and related plugins. Might have valuable insight
