### ISSUE TITLE
Custom maintenance page

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#356]
When the server is down for maintenance, create an HTML page styled to be simplistic but better than the 502 Gateway Error found with nginx.

Relevant links:
https://lincolnloop.com/blog/pro-tip-redirecting-custom-nginx-maintenance-page/

**Comment by TheRealHona** [comment]
This can't be externally PR'd without access to the nginx config I don't think? There could be a docker-compose which starts up a containerised nginx and the container on top of #403. An example of a similar thing is here: https://github.com/xbx/docker-compose-nginx-maintenance-page-example

**Comment by Gocnak** [comment]
Right yeah, it's like a static HTML page that can served, the key in that link in the OP is:
```
if (-f $document_root/maintenance.html) {
                return 503;
           }
```
and
```
error_page 503 @maintenance;
        location @maintenance {
                rewrite ^(.*)$ /maintenance.html break;
        }
```

This card was more focusing on getting a really simple HTML page, styled like the main site, to convey purposeful downtime.

**Comment by wallenben** [comment]
Can definitely do this if it's still an issue - how simplistic were you thinking?

**Comment by hexaflexahexagon** [comment]
Something pretty similar to the custom 404 page we have would be best in my mind. doesn't need to be extremely fancy, just letting the users know the website is intentionally down and will come back up.
