### ISSUE TITLE
Don't allow zone file uploads that have a different name than the maps

### ISSUE THREAD

**Issue by Hona** [momentum-mod/website#413]
Either this, or change the name of the zone to match the map name

**Comment by lambdadog** [comment]
I'm not convinced this isn't essentially already the case, looking through the code.

As far as I can tell the zone data is sent in the `tracks` field when POSTing to `/api/maps`, then is directly inserted into the database without any name associated with it.

**Comment by tsa96** [comment]
lambdadog's comment was completely correct, this was never an issue. New map submission doesn't care about filename either, it's just JSON.
