### ISSUE TITLE
Invalid map uploads shouldn't add to the queue

### ISSUE THREAD

**Issue by Hona** [momentum-mod/website#414]
There is no way to delete invalid map uploads from the Map Uploads page, and since it is invalid, the upload won't list in the admin Map Queue page

**Comment by tsa96** [comment]
Not sure if still relevant, will check

**Comment by tsa96** [comment]
This is completely irrelevant with the new upload system, which submits the map as a single multipart-form POST request, so never has to store a map without a submitted BSP in the "Needs revision" state.
