### ISSUE TITLE
Update map credits types

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#415]
Upon further reconsideration, the map credits types need some updating.

The AUTHOR type stays and becomes "anyone who worked on the map". It is implied with the order of the credits that the "top-most" name means the most important. For example, collaboration maps would list anyone who made a stage under this credit type.

CO_AUTHOR gets changes to become CONTRIBUTOR. These are people that gave assets, did very small work on the map, but still did work regardless to make the map. For example, people who made models out of the ramps, or provided original assets like textures to use for the map could be given this credit type.

TESTER stays exactly the same, and will be used to credit any testing whatsoever.

SPECIAL_THANKS stays exactly the same as well, and this is used for any miscellaneous credits, things like motivation or monetary support, etc.

On top of these changes, the credit entry should be updated to take in a small text field (varchar 255 should be good) for further explanation. This allows authors to be attributed to exactly what they made, or contributors for what exactly they contributed. For example, on a collaboration map, "author1" made stages 1, 3, and 5, so this text could be "Stages 1, 3, 5".

**Comment by tsa96** [comment]
We should do some general cleanup of credits during this.
- There's some duplicate code in the various map credits related Angular components
- Currently during map credits updates the frontend sends PATCHs for *every* credit, even if unchanged.

**Comment by tsa96** [comment]
This we absolutely want before map submission, so getting started on my current branch. Note we no longer use `varchar(x)` (not perf benefit over `text` in Postgres.
