### ISSUE TITLE
Gamemode timer circle is offcenter on mobile

### ISSUE THREAD

**Issue by Hona** [momentum-mod/website#442]
Example:
![image](https://user-images.githubusercontent.com/10430890/94331353-1d3d5400-000f-11eb-9f25-8128feee06e8.png)

**Comment by yi-yi-source** [comment]
![imagen](https://user-images.githubusercontent.com/62451782/97865733-6a38d800-1ce9-11eb-9daf-d4cbb5b01e39.png)
Also an issue on desktop in my second monitor (1366x768), looks fine in 1080p
