### ISSUE TITLE
Add public lobby tab

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/website#455]
Add a tab to view public lobbies on the website, perhaps in a similar format to `https://momentum-mod.org/dashboard/community/twitch`. 

![image](https://user-images.githubusercontent.com/62961532/97778935-16938680-1b51-11eb-9277-4c86ac9850de.png)

**Comment by TheRealHona** [comment]
Not sure if this is necessary since to play you’d have to open the game anyway

**Comment by TheRealHona** [comment]
It was decided that using the in game browser does this job
