### ISSUE TITLE
Component showing records two players took from each other

### ISSUE THREAD

**Issue by MichaelViera** [momentum-mod/website#478]
**A board that shows all the records two players took from each other**. 

![momentum](https://user-images.githubusercontent.com/80482179/110852233-6417c100-82b2-11eb-9035-f3f4c8c8f9be.png)

The list only shows records that the player had the LAST win on (regardless of lost to a third player or not).
The green color suggests that the player still holds the record.
The red color suggests that the player lost the record to a third player.

x_n_ is the number of times the player took the record from his/her opponent (s)he is compared against. 

The board should sort the taken records by x_n_ (from large to small). Those that have the same x_n_ could be sorted chronologically. It could also be an option to "roll out" all record breaks (regardless if they were last or not) in a complete chronology. This will perhaps also demand you to be more creative with colors.

If the red taken records (those that were taken but lost to a third player) get "beaten" back in such a way that the player doesn't get rank1 on the track, then it has no impact, the player's opponent will still keep the red-colored taken record with lower rank! Maybe it should be marked too, dunno (it should NOT be equalized with the green ones!!!). 

There are many possibilities. win-loss ratios could also be thought about. 

The point is to encourage competition and to give people a tool to measure players' skills. The most fought ones should be shown first because these have the players been most committed to.

**Most defended**

Closely related to my last paragraph, each player should have a list of their most defended records, regardless if they still hold them or not, those that they still hold could be colored green, those that they have lost should be colored red (equivalent with the first system). x_n_ should ofc. be used here.

**Comment by MichaelViera** [comment]
"The most fought ones should be shown first because these have the players been most committed to."

This is not exactly true. The most committed ones are the ones who stand highest in each player's most defended list. I mean, you can defend a wrcp against various players, but then lose to the opponent in the board 1 time and then take it back one time. That doesn't mean you haven't been committed to the wrcp! So it should be sorted by most defended, then it could be a custom option to sort by what I originally said (the most fought ones between you and him/her only)

**Comment by tsa96** [comment]
Very niche but okay, we're keen on doing lots of little independent Angular components and maybe we can discuss this more and turn it into some workable.

**Comment by tsa96** [comment]
Too specific, weird
