### ISSUE TITLE
Link Press Kit Page to Bottom of Main Page

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/website#492]
we need a page where anybody writing a blog/article/etc can easily go to quickly figure out what our game is about and access some needed resources. should be somewhere fairly easy to access on the main page and would be relatively simple. 

at a minimum it should include:
1. a bit about us and what we do, mission statement stuff
2. some statistics people can easily reference (like game downloads? idk)
3. (most importantly) easily downloadable high quality versions of logos, backgrounds, other assets.

some examples of existing press kits that we can reference are:
- https://www.annmariegianni.com/press-kit/
- https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by Hona** [comment]
Also make sure to give branding guidelines, like not changing the icon aspect ratio, changing colors, etc (the standard stuff)

**Comment by Gocnak** [comment]
Should it be on our main site or on our docs site? I think our docs site would make it way more approachable for editing quickly if we make any updates to our branding.

**Comment by hexaflexahexagon** [comment]
the idea is that people who are unfamiliar with the game will be the main ones using this so it should be accessible through the main site if at all possible (having the page itself hosted on the docs and linking to that on the main website might be fine as well but would be messy in my opinion). for example, on the chaos website a press kit link would either be on the "contact" page or added as a separate tab next to it, marked with an x here. 
![image](https://user-images.githubusercontent.com/62961532/117561803-01e7fc00-b068-11eb-82bd-2290b3492d57.png)

i'm not sure about where on our website this should go specifically due to our structure being a little different. our "about" header here just scrolls down rather than going to a separate page like on chaos, for example. 
![image](https://user-images.githubusercontent.com/62961532/117561889-a9652e80-b068-11eb-83b5-2d246e0b3537.png)

perhaps it could be added as another section down here somewhere but this section is already looking crowder so i'm unsure what's best.
![image](https://user-images.githubusercontent.com/62961532/117561998-96069300-b069-11eb-977e-7ca606872029.png)

that's where other websites seem to have them linked from what I can tell but it's really not too hugely important in the end. 
![image](https://user-images.githubusercontent.com/62961532/117562100-60ae7500-b06a-11eb-96f1-8b5a4c5e177f.png)

**Comment by Gravy59** [comment]
How about something like this?
[momentum guidelines.pdf](https://github.com/momentum-mod/website/files/6650373/momentum.guidelines.pdf)

**Comment by Hona** [comment]
Hi @Gravy59. Thanks for putting in the effort to make this, however we are making the press kit internally.

**Comment by Gravy59** [comment]
> Hi @Gravy59. Thanks for putting in the effort to make this, however we are making the press kit internally.

That was more of a preview. The one TraZox made looks much better.

**Comment by Gocnak** [comment]
Updated the issue as the "make press kit" was handled internally, but the work to add it to the main page of the site is still valid here. We'd ideally want this next to the Momentum copyright footer found in this image:
![image](https://user-images.githubusercontent.com/5162166/126935172-24e4462e-dcd1-4cdb-8d53-ccfac5011ef8.png)

So it would be like `Momentum (c) <year> | Branding` with `Branding` being a link to the PDF's URL hosted on the Momentum Mod site (in the static assets folder):
[Momentum_Branding_Guidelines.pdf](https://github.com/momentum-mod/website/files/6875679/Momentum_Branding_Guidelines.pdf)

**Comment by comatoad** [comment]
I can push this with #523 or PR for it directly after if that's alright with everyone 👍

**Comment by Gocnak** [comment]
You can do it together, that's fine with me!
