### ISSUE TITLE
Add link to OpenCollective page on website

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#502]
Momentum uses [OpenCollective](https://opencollective.com/momentum-mod) to accept donations. It would be good to have this page linked on the main page.

First thought is bare minimum: add it to the "Links" section, using the "gift" eva icon (`<nb-icon icon="gift">`), with the text "Donate"

Second thought is more involved and could come with a bit of a main page refresh (due soon with the engine update and branding update). It would be to make the OpenCollective link more prominent, like right below the "Play on Steam" embed in the main "header" section. Pending UX, and could actually be pulled out into its own card later.

**Comment by vindow** [comment]
OpenCollective has a [widget available](https://opencollective.com/widgets) but it seems to use <script> tags for the version that lights up when you hover over it which isn't something you'd want to add into an Angular project. There also a static image version which would be the easiest to add but it doesn't react to being hovered over. I could remake the hover effect/look of the using CSS but the look of the widget itself is a bit too bright(?) for the page:
![image](https://user-images.githubusercontent.com/5974776/118203971-06b70200-b412-11eb-8fa6-64e84bf556ad.png)
It would probably be easily possible to use CSS to remake the button so I could change the color of the button and add the hover effect but OpenCollective doesn't seem to have any logo usage guidelines that I could find with a quick cursory search. I'd have to assume you couldn't change the OpenCollective logo colors anyways so the best I could imagine would be to use the same blue for the button (not the OC logo inside the button) that the Momentum Mod logo uses. It would probably look something like this (quick dirty image edit):
![image](https://user-images.githubusercontent.com/5974776/118204936-32d38280-b414-11eb-8203-7ec64b78f4d5.png)


Regardless, the redesign of the website is coming soon™ so should I go ahead with adding in a custom CSS widget or should I just slap the static one in as a temporary thing for the current website?

**Comment by Gocnak** [comment]
So let's go with both option 1 (add to links with icon) where it can show up next to the Steam link (so it'd be second from the left), and option 2 can be the image right below the steam embed, just like your second image.
