### ISSUE TITLE
Enforce new ESLint rules

### ISSUE THREAD

**Issue by bakapear** [momentum-mod/website#520]
If #519 gets merged and we move to ESLint, it would be best practice to lint the entire project with the new rules ESLint has to offer. Some added rules might not be desirable for some, which is why I created this issue to discuss this further.

Currently disabled to match old TSLint rules: 54eeb6f
https://eslint.org/docs/rules/

**Comment by wallenben** [comment]
Looking into this 👍

**Comment by tsa96** [comment]
Done in rewrite (my ESLint rules are HARDCORE)
