### ISSUE TITLE
Top 10 Run History

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/website#522]
For the upcoming feature update on the website, a nice idea for ways to explore the data is to implement a History of the Top 10 runs, allowing you to scroll through time, watching the wr and the top10 slots change and improve, in a similar manner to the [youtube channel ABACABA (example video: minecraft any%)](https://www.youtube.com/watch?v=6eF4vD7D_Qc)

This is data we already have and are storing in the database, but currently have no mechanism to display. It's a neat idea IMO, and something nobody else is currently doing.

**Comment by tsa96** [comment]
Weird, think records are enough, at least for now. https://github.com/momentum-mod/website/issues/368
