### ISSUE TITLE
Update main page BG branding to match new brand direction

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#523]
Out with the grey icons, in with the light and lively 3D crystalline geometry!

Using a video tag that is streamed in (use `preload=metadata`), and use the photo as the "banner":
[MomentumLight.zip](https://github.com/momentum-mod/website/files/6875708/MomentumLight.zip)

See the gamemode component for how it was done there:
https://github.com/momentum-mod/website/blob/staging/client/src/app/pages/main/gamemodes/gamemodes.component.html#L45

**Comment by Gocnak** [comment]
Note: It may be extremely beneficial to re-encode the preview banner as `webp` and reduce the size down. These files were yoinked from the game repo as the background textures, which handles loading (local files) much faster than streaming the file from our server will be.

**Comment by comatoad** [comment]
can definitely r&d this. quick thoughts - do you want an encoded mp4 for the non-webp audience?

**Comment by bakapear** [comment]
Most browsers support webp. Just add a fallback to a static image in case they don't.

**Comment by Gocnak** [comment]
To clarify: the video is `webm`, and the banner would be best re-encoded from dds to `webp`. We already exclusively use `webm` and some `webp` for the gamemode videos/images so a double-encode to MP4 would not be necessary I think! I'm also fine with not supporting relatively older browsers.

**Comment by comatoad** [comment]
Quick update - .webp and .webm are implemented and looking nice. Had to do some minor tweaking to get the cool "fade to grey" effect working in a video container - working on a solution for the blur in the top-left next. Looking at this, I think some of the fonts might clash pretty heavily with the video (see below). Thoughts? I could do a quick color swap or change the design, a tad hard to see the status bar as it is.
![image](https://user-images.githubusercontent.com/72104872/127435988-e455227e-733f-48e3-99a5-1cf4e1a70ede.png)

**Comment by Gocnak** [comment]
Oh yes the status bar should definitely be updated! Instead of being fully opaque it could be partially transparent, to give it a slight black background?

**Comment by comatoad** [comment]
Sounds good to me! I'll post a mockup here later. I don't think the video clashes with anything else but I'll test for mobile tomorrow.

**Comment by comatoad** [comment]
So here's what the navbar looks like with a 'half-transparency' navbar using Momentum's black color scheme:
![image](https://user-images.githubusercontent.com/72104872/127579559-cc4a85c3-2e74-4567-bd87-9a14033bcf93.png)

Finding the best balance might be a battle for someone on the UI/UX side internally to make sure it respects the momentum color scheme, but I also found the the navbar looked fine using the momentum blue color scheme - could be an option if there's worry about the gradient clashing with the navbar. Let me know what you think - I can PR for this and issue 492 whenever

**Comment by Gocnak** [comment]
Yep that photo looks fine! And then when you scroll down it gets a bit darker right? Either way I think that looks perfect and ready for the PR!

**Comment by Gocnak** [comment]
Pushed it live, the bottom gradient seems to be a bit much on 1440p:
![image](https://user-images.githubusercontent.com/5162166/127604321-e6ff133a-57b9-4fa4-bf40-37474e012ca1.png)

Nudging it closer to 100% seems to make it somewhat better though!
![image](https://user-images.githubusercontent.com/5162166/127604444-df8bb676-9514-4782-b94c-8c79c0dc9950.png)

**Comment by comatoad** [comment]
Hmm.. had a friend try to recreate this error on his 2K and couldn't replicate it. Perhaps changing the transparency variable to 100 viewport height could solve it? I pushed what I think could be a fix to my fork (and a quick autoplay fix) - let me know if that solves the issue at hand

**Comment by Gocnak** [comment]
So I dug into it some more, it's because I use tree style tabs, which is a vertical sidebar for me. There's a black bar at the bottom which is behind the video -- so the video isn't scaling the height to match my viewport.

![image](https://user-images.githubusercontent.com/5162166/127727551-4fb59b36-06da-4ab3-a746-fe9b1e79dd0d.png)

Squishing my sidebar over makes it fill more:
![image](https://user-images.githubusercontent.com/5162166/127727563-9edd7e61-9782-41ff-95ba-fd443044e473.png)

Is it the height of the video? How it's fitting maybe? Would it be possible to stretch the video?

**Comment by wallenben** [comment]
I think it might be because of one area where I used percentage scaling - on my portrait monitor everything was way off, for a similar reason I imagine. Switching to viewport-height scaling should do the trick. I have this (and a few other) bugfixes ready to PR (some tag changing to make autoplaying the video better), so if you want I can submit that while I work on implementing a new background for the dashboard.

**Comment by Gocnak** [comment]
Yep sounds good!
