### ISSUE TITLE
404 page has poor visibility with new background image

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/website#528]
![image](https://user-images.githubusercontent.com/62961532/127974106-263bd2c5-24fd-477b-87c7-63a72675a9ad.png)

See https://momentum-mod.org/asdfsd

**Comment by bakapear** [comment]
Put big stripe behind it maybe?

![image](https://user-images.githubusercontent.com/13366049/128368505-b5cf21d0-fa58-4fa6-b557-e2656969b96f.png)

**Comment by hexaflexahexagon** [comment]
looks good to me. @Gocnak thoughts?

**Comment by Gocnak** [comment]
Fine with me, yep!

**Comment by wallenben** [comment]
I can do this in parallel with #356 - I imagine we want consistency between the various server messages

**Comment by wallenben** [comment]
This is what I have currently in dev - thoughts? If the gradient is a bit much that can be removed super easily. 
Some resizing will be done, just to make sure everything is centered properly - should be a pretty close 1:1 of what's above
![chrome_X6mw2HFh0I](https://user-images.githubusercontent.com/72104872/128614989-3573e49a-bb96-434b-8b1e-5482612236e8.png)
