### ISSUE TITLE
Filtering the "browse maps" page doesn't accept the enter key

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/website#533]
At `https://momentum-mod.org/dashboard/maps` typing something into the box to search for a map and then hitting enter does nothing. You have to mouse over to the 'search' button instead which is unintuitive and should be changed.

![image](https://user-images.githubusercontent.com/62961532/128599123-b3d88c26-e364-4d3a-8488-a53b2df3b0a4.png)

Also worth noting is the fact that selecting a gamemode from the dropdown next to the search box also requires you to hit the 'search' button to update your results. Maybe this should automatically apply when selecting a different gamemode instead. 

![image](https://user-images.githubusercontent.com/62961532/128599220-f402e41a-f6b2-4818-b4cb-e398c2dda7ba.png)

**Comment by wallenben** [comment]
Was just looking at this the other day - I can def look into this if nobody else is in the interim
