### ISSUE TITLE
Switch to TypeORM for backend

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#552]
We currently use sequelize which is nice but we're on our way to TypeScript and need a fitting ORM.

https://typeorm.io

**Comment by TheNerdMan** [comment]
I was going to do some DB to TS classes this evening, would you like me to look at creating it using this right now? Or hold off and create generic TS classes that could be easily ported to this

**Comment by TheNerdMan** [comment]
In the last commit I've mentioned that a model needs a bit more as currently in the DB is a JSON struct that could do with a ViewModel.
``` TS
// TODO: Better model for this 
export class MapZonePropertiesModel {		
	properties: string; //JSON struc needs work
}
```
I think this model is fine as models should represent exactly the DB schema, however there is nothing stopping us creating a ViewModel for this that has more description of the properties.

**Comment by TheNerdMan** [comment]
We are using Prisma now (along with NestJS)
