### ISSUE TITLE
🐛API-Docs test execute seems doesn't work properly

### ISSUE THREAD

**Issue by Fustie** [momentum-mod/website#560]
I try to make an a test request on https://api.momentum-mod.org/api-docs/, but it returns me `TypeError: Failed to fetch`

**To Reproduce**
1. Go to '[API-Docs](https://api.momentum-mod.org/api-docs/#/)'
2. Click on any method
3. Click try it out
4. Click execute 
5. See error

**Expected behavior**
Good response from any method, like users/ or another

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Cent Browser
 - Version 4.3.9.248

**Website Information**
 - Version/Git Commit: [ce3b6878367453740cdf74a4298e992d73bddfaa](https://github.com/momentum-mod/website/commit/ce3b6878367453740cdf74a4298e992d73bddfaa#diff-183dfcbb2c260fee7e3468389eaf038313e4ef51d52a3d8627590ba8daab4ce8)

**Comment by tsa96** [comment]
This isn't an issue in the rewrite, and we don't care about fixing on the old API since it'll be dead soon.
