### ISSUE TITLE
Add "Map Unavailable" Status

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#570]
Maps will most definitely need to have a "temporarily unavailable" status to them that can be represented in game. This allows admins to make any emergency edits or updates as necessary, 

- Prevents run uploads (on boot of map and on run upload a warning toast should appear on the game client)
- Zones unavailable (from the site, users can still play locally)
- API endpoints for the map return empty (with this status as some error code)

**Comment by tsa96** [comment]
New `DISABLED` state provides all this. Backend side is already done, some frontend work still needed for updated map edit page but I don't think this issue is really relevant to that, so closing.
