### ISSUE TITLE
Filtering a leaderboard for 'ranks around me' gives 403

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/website#577]
**Describe the bug**
Trying to filter by 'ranks around me' on at least one map (`bhop_arcane`, id 18) gives the error below.

![image](https://user-images.githubusercontent.com/62961532/147517202-2dafc51c-4774-4fe3-9051-c8821bfac041.png)

Given the nature of this bug needing ranks around the user's current time it may not be easily reproduceable for everybody who doesn't have my exact time on bhop_arcane. if that's the case I can try and give more details if needed, it seems to happen very reliably for me.

**To Reproduce**
1. https://momentum-mod.org/dashboard/maps/18
2. Filter -> 'Show ranks around me' -> update
3. bug

**Expected behavior**
No 403 and the filter works as expected

**Desktop (please complete the following information):**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

**Website Information**
 - Version/Git Commit: current latest `fec69ce0ee670286e5ea1a1c9d97b22d37dfb16a`

**Comment by TitomakaniJr** [comment]
I tested this as well and it looks like it happens for any map you don't have a current run on.

The relevant API request is `api/maps/{MAP_ID}/ranks/around?limit=10` and based on the following response it looks like the services are properly handling the case.

`{
    "code": 403,
    "message": "No personal best detected"
}`

I believe this is a front-end issue which would involve not displaying an error toast if the user doesn't have runs. More appropriate might just be a warning toast with more details like `You have not completed this map`.

Alternatively, if a request is made to get user data on a maps page load the `Show ranks around me` radio button could be hidden if the user doesn't have valid runs.

Based on the report it seems that @hexaflexahexagon does have a completed run on `bhop_arcane` in which case there might be another issue.

**Comment by tsa96** [comment]
403 doesn't make any sense as a response though. I'll check this out when we hook the frontend up to the rewrite.

**Comment by hexaflexahexagon** [comment]
unless my time was old and got wiped it looks like I don't have an arcane PR, must have mis-remembered and done it in mapping mode or something. at any rate i don't have one currently and can still replicate the parent issue here and get the 403 warning.

**Comment by tsa96** [comment]
Maybe still an issue now, idk

**Comment by tsa96** [comment]
This endpoint will be removed in leaderboards refactor around 0.11.0 so not worth fixing. Keeping it tracked here to avoid duplicates, but nobody should work on this.
