### ISSUE TITLE
Defrag Youtube Video unavailable

### ISSUE THREAD

**Issue by ritzzzy** [momentum-mod/website#581]
![firefox_Z2XhM3wPO3](https://user-images.githubusercontent.com/67691874/147860593-80895146-b5f9-4f87-ab34-c11eba8f0917.png)

**Comment by OstojaOfficial** [comment]
Works fine.

**Comment by hexaflexahexagon** [comment]
looks like this was updated in 651eb7f3d6dcb060b97a2df1fc0f8132c48c3aab but the issue never got closed. good catch!
