### ISSUE TITLE
♻️ Implement NestJS backend

### ISSUE THREAD

**Issue by TheNerdMan** [momentum-mod/website#582]
After much conversation we are making the decision to create refactor the back end using NestJS.

You can find this project open in its own branch `nestJS`.

This is a ***colossal*** task, so any and all help is welcome. 

The full tech stack will be;

- NestJS (Routes and API logic)
- Prisma (ORM)
- PostgreSQL (DB)
- Backblaze - using AWS SDK (Media hosting)

**Comment by tsa96** [comment]
Besides https://github.com/momentum-mod/website/issues/750, we're done!!!!!!!!!!!!!!!!
