### ISSUE TITLE
Server Dockerfile should be updated to follow best practices

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#584]
As seen in https://github.com/BretFisher/node-docker-good-defaults

We should be:
1. Using the 'node:12-alpine' base image for a smaller production docker image
2. Using the 'node' user instead of defaulting to root (security vuln!!!)
3. Getting the test, dev, and prod environments to be as close as possible (see #583 for one step towards that)
4.  Be more careful about what all is being packed into the docker image (node_modules, etc)

**Comment by tsa96** [comment]
Shouldn't be hard, node dependencies get handled by webpack now anyway
