### ISSUE TITLE
Redesign map upload form for 0.10.0 map submission

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#603]
~~Current upload form is pretty crummy.~~

~~- The zone file upload component should be grouped with all the other file uploads~~
~~- The Youtube URL can move to its place in the "description" section~~
~~- The authors search does not allow scrolling (limits to 5 people?) so searching for some common words never shows the~~ ~~profile you need, especially placeholder accounts~~
~~- Remove the "markdown is supported" bit. The game can't parse markdown and doesn't seem necessary.~~

~~**Additional Context**~~
~~Discussed in #website on 25/02/22.~~
~~Note to contributors, this form is only visible to admins, so set your role to `8` in the DB.~~

Re-purposing this issue for the map submission project.

First, let's keep naming consistent and rename files/classes from "upload form" to "submission form".

## "Files" page 
Add a link to the map submission page on the docs - that will contain a detailed explanation of the entire process. Make sure the UI really nags people to read it. https://github.com/momentum-mod/docs/issues/323

Entry for a VMF (optional), with an info tooltip saying that whilst uploading a VMF is not required, we encourage people be open with their maps, decompiling is possible anyway, and we that still have rules about stealing people's content.

Zones file should be here, not description page. We'll be storing zone data as JSON in the future, rather than KV1, which will make parsing much easier and mean we can remove the dependency on `node-steam/vdf`.

## "Description" page

A "display name" entry, explaining difference between that and filename.

Youtube URL entry should be here, not Files.

A dropdown for "Submission Type" using the `MapSubmissionType` enum.

A section for a new MapSubmissionSuggestions component, which should `ngFor` over every `Gamemode` and provide an option for
- tier (int [1-10])
- ranked (bool)
- comment (string)
with some descriptions for each (maybe easiest to put at the top of the section, not each instance)
We're gonna have a *lot* of submodes in the future so ideally have a quick way for people to hide modes they don't care about. Also we could use existing selections of modes to automatically hide modes they're [incompatible with](https://github.com/momentum-mod/website/issues/812#issuecomment-1674914197).

## "Credits" page
Stays the same, the main improvements we're looking for here are coming in #415 and https://github.com/momentum-mod/website/pull/768. I may clean up some of the Typescript in the credits components during #415, or even split up the editable and non-editable bits in separate components.

## "Testing" page - NEW
Have a paragraph or two explaining how testing process works, and link to the docs page again.

Simple toggle button or something for whether they want private testing or not. If yes, show a user search component (note to self - if I'm working on this and [#768](https://github.com/momentum-mod/website/pull/768) isn't in by then, may as well finish it up myself). Don't need to force people to add testers, they may want to do it later, not a big deal.

## "Review" page
Not much new, just need to display all the new stuff.

**Comment by AWildErin** [comment]
As per what was said on the discord in `#website` we can probably convert the sections into a single scrollable area. I'll be playing with this alongside the current tasks that need to be done for this issue as well.

On top of that, probably gonna rework how the map file and map thumbnail buttons are, probably do something similar to the zones area where, after you add the file, it changes to a delete button. I'll play around with that. 

Just thought I should add these on here just in case they get lost in the channel history!

**Comment by tsa96** [comment]
Blocking off for now, as 0.10.0 map submission changes are bound to affect this in loads of different ways, so worth waiting until that's more specced out. Though the author search credits-related stuff is now being tracked in https://github.com/momentum-mod/website/issues/759 instead, and can be worked on now.

**Comment by tsa96** [comment]
Okay, have updated the issue description with new stuff, should be good to go. I'm planning on working on this, but won't get to it for a couple of weeks at least. If anyone else is particularly keen, give me a shout.

**Comment by tsa96** [comment]
Map files and map submission versions should always *start with* the map's `fileName`. E.g. for `surf_map`, `surf_map_a10` is okay, `testmap123123` is not. Backend checks this, frontend should warn

**Comment by tsa96** [comment]
`creationDate` is a funny one. For ports, the date should be when the original map was published. For original maps, we're probably off using the latest map submission version. Do we have a reason to allow an earlier submission date for an original map?
