### ISSUE TITLE
Post to webhook when new map is fully published

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#607]
When a new map is fully published (admin approved and clicked green check), we should post to (a) webhook(s) announcing such news. This will allow us to be flexible with our game's announcements on Discord.

**Comment by hexaflexahexagon** [comment]
idk if these are something that would just be available in our discord server or if people could use them in their own servers, but if they can then it could be cool to consider some sort of separate event for WIP maps being added/updated/something, making it easier for people to get slammed in the face in discord when something needs testing. not sure at all about the mechanics behind webhooks and how cumbersome that may be to add, as people will probably only actually want a few gamemodes or events to get posted in their discord channels. if people were able to select for example:

I want the following map notifications:
- [ ] finished
- [ ] WIP

For the following gamemodes:
- [ ] surf
- [ ] bhop
- [ ] etc

then that'd be sick

**Comment by TheNerdMan** [comment]
So just doing some quick research on Webhooks as while I've used them I
haven't developed them. Looks like we'd basically need to collect a bunch
of endpoint URL's that we'd want to post to when a map is complete/updated.
And we would need to set it up in a way where those Webhooks are tied to a
user account too.

Here is a super simple implementation using NestJS.
https://www.fullstacklabs.co/blog/how-to-implement-webhooks-using-nestjs.
Again we'd need to update our DB schema somewhere to include a webhooks
table/column and draw up a whole UI/UX flow for giving us a webhook
endpoint.

Here's a list of some of the things that bounce around my mind when
thinking about this feature:

   - Do we store webhooks against a user?
   - How many webhooks can each user have?
   - How long would it take to post to 1000s if not 100,000s of webhooks?
   - How do we store notification options? Against the user or the webhook
   itself? (I'd prefer the latter)
   - How can we make sure that this posting doesn't affect API performance
   when running?
   - Should we care about webhook's response, if so should we warn users
   that its not 200ing and after multiple missed days delete the record? (Or
   at least mark as inactive so we don't post to it)

But I personally think that this should be handled by the bot to begin
with. Then when we've given it more thought and have a bit more of an
existing method of notifying users when maps change status, then this
should be looked at being implemented.

**Comment by Gocnak** [comment]
If it's going to be in people's servers, it'll be a bot integration for sure.

**Comment by TheNerdMan** [comment]
Yeah my thought exactly, this feature does allow for more collaborative development (e.g. users would be able to make their own dumb downed MMod bot) but honestly I think this should be put as a super low priority and this should be handled by the discord bot first, then maybe this later down the line

**Comment by tsa96** [comment]
This is really complex, we'll discuss more soon

**Comment by Gocnak** [comment]
The backend will have an env var for the webhook to post to. It will be an announcement channel, and can ping a specific role that users can opt into in the server to get notified. Other servers can "follow" the channel to get it in their servers, this will not be in a Discord bot.
