### ISSUE TITLE
✨ Implement Fastify Adapter for better API performance

### ISSUE THREAD

**Issue by TheNerdMan** [momentum-mod/website#613]
# Overview
As we are rewriting in a new framework it is important to apply good foundations for future developers to build off of. One of these foundations is performance (without sacrificing anything).

# Describe the solution you'd like
@tsa96 mentioned in discord about using Fastify, and after some quick research I think it would be a good idea to use. Due to NestJS's easy drop in/out adapter for it.

# Describe alternatives you've considered
I was worried that there may be unforeseen consequences (λ) in dropping this in. If so @tsa96 and I quickly brainstormed some fixes that could work, if not then we would have to continue using express. Those fixes could be;
- Attempting to load both adapters and using a custom `AbstractHttpAdapter` to decide which adapter to use.
- Attempting to load both adapters and using a custom `AbstractHttpAdapter` to first attempt to use Fastify then fallback to express.
- Using the `config.ts` to decide which adapter should be used on app load.

# Additional context
[A blog post describing the differences (might be an advert?)](https://medium.com/@vishalims095/express-vs-fastify-9a4d052c28e1)
[NestJS Docs explaining how to implement Fastify](https://docs.nestjs.com/techniques/performance)

**Comment by tsa96** [comment]
Going to leave this open for a little bit as I want to get back to it in a bit, but removing from the endpoint implementation board. It definitely looks like a major headache in terms of Passport and file upload.

**Comment by tsa96** [comment]
Donion rings
