### ISSUE TITLE
Restyle outgoing page

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#740]
Assuming we keep it, that is. This thing looks abysmal currently, and the HTML has some absurd nesting, worth just scrapping and redoing after we [consolidate it into the main dashboard](https://github.com/momentum-mod/website/issues/739). So, once that's in (maybe we'll do it at the same time), just make an cleaner version of this within the dashboard page.

![Momentum_Mod_-_Google_Chrome10,05,23,072028](https://github.com/momentum-mod/website/assets/35813309/4b723367-9279-4305-82ef-da009fb984e8)

**Comment by odwngit** [comment]
I could take a crack at this, is this required to be in Angular? Or is this pure html, css.

**Comment by tsa96** [comment]
This will be in Angular, it shouldn't need any specific Angular components be needs Angular-specific work to get the section embed in the main dashboard page - definitely recommend some general Angular experience before attempting any frontend stuff. Also, I need to at least get my `nx` branch in first before this can be touched, and maybe best left until 739 is finished entirely

**Comment by tsa96** [comment]
Closing, https://github.com/momentum-mod/website/issues/752 means we can just remove this garbage completely
