### ISSUE TITLE
Front page mentions Chaos Source

### ISSUE THREAD

**Issue by ozxybox** [momentum-mod/website#741]
### Describe the bug

1. Go to https://momentum-mod.org
2. Scroll to "ABOUT THE GAME"
3. Text currently mentions "Chaos Source Engine".

![887D4EFD-72E3-439E-B2BB-A5B3396729F8](https://github.com/momentum-mod/website/assets/24679671/1f836b7d-b778-4803-8721-2d82f7b9de54)

### Expected behavior

It should say "**Strata Source** engine" instead of "**Chaos Source Engine**".  Highlighted portion of the text should only be on "Strata Source", as the title of the engine is "Strata Source", not "Strata Source Engine" or other such. 

### Operating system and browser

- OS: iOS
- Browser: Safari

### Website information

It’s the version currently live on the website as of May 14th, 2023.

**Comment by tsa96** [comment]
Thanks, good find. We're actually completely remaking this site in the future but since it's so public-facing, worth fixing now.
