### ISSUE TITLE
Remove pointless createdAt and updatedAt entries, use SELECTs better

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#753]
We should not be store this data when it doesn't need to be, not should we be `SELECT`ing it when we don't need to.

So, go through the schema and remove these (and any other redundant columns) where possible.
Also, there's bound to be stuff that we don't need to fetch on some calls. Remember, it's more memory efficient only SELECT the stuff you need.

Related to https://github.com/momentum-mod/website/issues/745, I'm going to assign myself and do both at the same time

**Comment by Gocnak** [comment]
Note that it may be a side effect of sequelize creating this for every entity. We will definitely want date fields for things like runs and maps (accomplished dates) but I agree `updatedAt` isn't needed except for maybe maps only.

**Comment by tsa96** [comment]
https://github.com/momentum-mod/website/pull/781 improves SELECT usage a lot. Going to leave this open until we fully clean up the actual `createdAt`/`updatedAt` columns - probably once we implement the 0.10.0 DB schema changes.
