### ISSUE TITLE
Move backend bundling to better bundler

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#775]
We're bundling the backend with webpack currently, whilst not overly slow, may as well switch to esbuild as we migrate the frontend (https://github.com/momentum-mod/website/issues/748) as well .

**Comment by tsa96** [comment]
Never mind, forgot esbuild still doesn't have full decorator support. There's some hacky ways of getting around it, but not worth it. Closing for now, maybe we'll have another go with esbuild (or Turbopack?) in the future?

**Comment by Gocnak** [comment]
Reopening, we should prefer to keep this issue open because webpack is *insanely* slow, and whilst we don't need to use esbuild, we should definitely look into other packers in the future, so I'll rename the issue to better fit that goal.

**Comment by tsa96** [comment]
I don't have exact numbers but webpack takes roughly a second on a backend - don't think we need to worry about this unless some new Nx generator comes along that can easily replace webpack

**Comment by tsa96** [comment]
Note that Nest has SWC support now, so SWC compilation *might* be possible, but SWC bundler isn't yet a thing and probably never will be. So SWC + Webpack probably makes sense, maaybe Turbopack could be used as a drop-in for Webpack in the future.
