### ISSUE TITLE
Make /users GET search by alias case-insensitive

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#796]
This is really really easy, see https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#postgresql-provider
Then write an E2E test that it successfully matches a name with differing case.

**Comment by emmanuelmoon** [comment]
Hi, can I do this? This'll be a good first issue for me.

**Comment by tsa96** [comment]
Yup, go for it!

**Comment by emmanuelmoon** [comment]
This test would be in 'prisma.e2e-spec.ts', right?
