### ISSUE TITLE
Require submitted BSPs be bspzipped

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#836]
`bspzip` LZMA compresses each lump in a BSP, drastically decreasing filesize, and AFAIK has no runtime cost in-game. Hosting large files costs us money and it's not hard for mappers to `bspzip` their maps, so let's require them do it.

Parsing just the *header* of a BSP is relatively easy, I forget the exact data structure but there's entries in each lump section in the header with the compressed and uncompressed size (or something similar, SCell says it's doable so I trust him). Let's just parse that (we could pull the basic binary reader functions out of `@momentum/replay` if needed) and check compressed size is significantly lower.

Should be possible to integrate this in both frontend and backend. Adding a BSP file is on the first parts of the upload form, so do the check then and show an error if it's not zipped. Backend `/maps POST` should 400 if not zipped.

**Comment by GordiNoki** [comment]
Is there a known list of uncompressable lumps? I only 35 (LUMP_GAME_LUMP - Game-specific data lump) and 40 (LUMP_PAKFILE - Embedded uncompressed Zip-format file)

**Comment by GordiNoki** [comment]
https://developer.valvesoftware.com/wiki/BSP_(Source)#Lump_compression
> There are two special cases for compression: LUMP_PAKFILE is never compressed and each of the game lumps in LUMP_GAME_LUMP are compressed individually

So I guess only those should be ignored

**Comment by tsa96** [comment]
I'm sorry, I should've self-assigned this, or at least said I was doing part of it.

The BSP parsing is done (https://github.com/momentum-mod/website/blob/5ad4e5851d889397da62745ab9db45a5ee58964f/libs/formats/bsp/src/bsp-header.ts), on my `frontend-map-submission-1` branch, though the file is moved on my latest branch. Everything is a big clogged up right now as we wait on review.

So far I've only hooked it up to the frontend (as an Angular validator, if you want to do the backend stuff go ahead, but you'll have to work off of my latest branch in review (refactor/frontend-cleanup)
