### ISSUE TITLE
Admins can not completly remove bans

### ISSUE THREAD

**Issue by GordiNoki** [momentum-mod/website#845]
**Describe the bug** Bans are not updated when you try to delete them all
**To Reproduce** Steps to reproduce the behavior:

1. Go to 'edit profile' page of any user that has bans
2. Remove every checkbox
3. Click 'save changes' button
4. Update page
5. See that bans haven't changed

**Expected behavior** "bans" field of user to turn 0, all checkboxes to be disabled

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox

**Website Information**

- Version/Git Commit: e62d2c82972f8b1b8c77d9051c5290ecec0f8e2a (2 commits behind current main)

**Additional context** The reason may be an error when checking the existence of the "bans" field in update data, cause it's value is 0

**Comment by tsa96** [comment]
Yup, noticed this yesterday! We're checking for truthiness rather than strict undefined in one place that results in no action if `roles` is 0.

**Comment by Gocnak** [comment]
Was this fixed in a recent PR?

**Comment by GordiNoki** [comment]
Yes, fixed in af7b4cc

**Comment by tsa96** [comment]
Ah yeah, I thought this was a frontend change but no, just a backend bug

**Comment by GordiNoki** [comment]
@tsa96 Have you fixed the same bug with roles tho?

**Comment by tsa96** [comment]
Don't see where it would occur in the code for roles. Probably should've added E2E tests for both bans and roles, but busy with other stuff and not sure it's worth a dedicated PR. If you want to, feel free!

**Comment by GordiNoki** [comment]
Oh, it was fixed long ago. Whatever
