### ISSUE TITLE
Level indicator Angular component

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#870]
Panorama has a small component for showing user level and prestige icon. It's relatively simple, and all open source. We should do an identical component in Angular.

https://github.com/momentum-mod/panorama/blob/master/layout/components/level-indicator.xml
https://github.com/momentum-mod/panorama/blob/master/scripts/components/level-indicator.js
https://github.com/momentum-mod/panorama/blob/master/styles/components/level-indicator.scss

Animations don't matter, they're only used for when the player levels up in real-time ingame. What's important is that we get the same colours and prestige icons.

Note that whilst the colours used aren't currently in our website repo or Tailwind config, we definitely want them in the future. I'm not 100% sure if they'll be the base of full colour palettes (that would be nice), but I'll get them organised in the new [*styling* repo](https://github.com/momentum-mod/styling) in the near future. If I haven't done that by the time someone else picks this up, nag me about it.

Here's an image for reference, though I assume anyone working on this probably has access on Steam already, but if not, just contact me for one.
![Momentum_Mod_-_DX1105,12,23,103505](https://github.com/momentum-mod/website/assets/35813309/bd3e7327-4d5e-4996-9bb8-e8326344689e)

**Comment by tsa96** [comment]
Oh, and launch the game with `-dev` and open the controls library (bottom left of main menu) to see all the variants (screenshot below)

![Momentum_Mod_-_DX1105,12,23,104254](https://github.com/momentum-mod/website/assets/35813309/73e6dc9c-0e9f-4962-800b-3942f50f714d)

**Comment by ianwillis98** [comment]
> ... I'll get them organised in the new [styling repo](https://github.com/momentum-mod/styling) in the near future. If I haven't done that by the time someone else picks this up, nag me about it.

Hey Tom, nagging about the style repo -- I'd like to work on this issue, but don't want to step on any toes

**Comment by tsa96** [comment]
Yeah hmm, I've been doing some work on that repo tonight, but I'm not sure when those palettes will be completely finished. Honestly, I'm not sure it's worth doing a full range of palettes right now anyway, so we could just bring those color values from Panorama into Tailwind as e.g. `red-500` and not do other reds, and do more if we need them.

Still, with backlog of PRs in review right now, this probably isn't the best issue to pick up. If you're really determined, you could work off of my more recent branch in review, but you'd have to mess around with rebasing stuff quite a lot in the future.

In Twitch chat today you said you were interested in test-related stuff, would you be interested in https://github.com/momentum-mod/website/issues/868? This would be a really good issue to get more used to the codebase.

Also as an aside, are aware of the #website channel in our Discord? If you're not a Discord user at all I'm happy to keep communicating on here (I'll try to respond faster in the future), but you'll usually get a faster response from me on there, and better for back-and-forth discussion like picking areas to work on.

**Comment by ianwillis98** [comment]
That sounds good to me -- I'll take a look at #868
