### ISSUE TITLE
Pressing enter on map submission form text inputs creates new suggestions

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#948]
Pressing enter when any `<input type="text">`  calls the `(click)` output on the [`map-leaderboards-suggestion` "Add Leaderboard" button](https://github.com/momentum-mod/website/blob/2782f6d7a6eb58ee950286dfaa2bc6af15ef5c14/apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboards-selection.component.html#L1). I have NO IDEA why it's happening. As far as I can tell it's only the text inputs, maybe some misconfiguration of the overall form.

**Comment by kanoka42** [comment]
Fix in my branch [here](https://github.com/kanoka42/website/commit/3300835bbed47b88a5b51efb5ad847d7fcf6e153)

**Comment by GordiNoki** [comment]
The actual issue is that [default button type is "submit"](https://stackoverflow.com/questions/31644723/what-is-the-default-button-type) and submit buttons trigger their `onclick` event when enter is pressed on text field in the same form. @kanoka42 's solution looks good
