### ISSUE TITLE
Negative Map Favorites

### ISSUE THREAD

**Issue by Atticus1423** [momentum-mod/website#972]
Maps on the website can reach negative favorites

1. Go to https://staging.momentum-mod.org/maps/beta
2. Click on a map
3. favorite the selected map
4. reload the page
5. unfavorite the map

Reloading the page should save the favorite count

![Screenshot (580)](https://github.com/momentum-mod/website/assets/174031880/0bcdfe69-91fc-46b6-8b4b-ff4546026fa5)

- OS: Windows 10 Home
- Browser Thorium
- Version 124.0.6367.218 (Official Build) (64-bit)

**Comment by tsa96** [comment]
Yup I can replicate, thank you! Not completely sure what's going on, shouldn't hard to figure out though.

**Comment by tsa96** [comment]
Closed by #1004
