### ISSUE TITLE
It's possible to set a future date as a map creation date

### ISSUE THREAD

**Issue by Natanxp2** [momentum-mod/website#975]
1. Go to 'Map edit page'
2. Click on 'Creation date'
3. Set it to a future date
4. Update the map

**Expected behavior**: It should not be possible to set a future date as a map creation date

![image](https://github.com/momentum-mod/website/assets/19735381/0a38015f-3751-4798-ad43-585567921d85)

**Comment by tsa96** [comment]
Lmfao
