### ISSUE TITLE
Placeholder suggestions still visible for approved maps

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#977]
https://staging.momentum-mod.org/maps/ahop_glick

Created this map with a placeholder user, approved it (using disabled -> final approval -> approved hack), produces this:
![image](https://github.com/momentum-mod/website/assets/35813309/9b8d2aee-aa01-436d-b360-ab57d25a65d4)

Not sure where the RHS one is even coming from, I thought the placeholder suggestions were stored on an array on the `MapSubmission` entry, shouldn't be including requesting that expand in the request anyway.

**Comment by tsa96** [comment]
@Gocnak The original name was correct! You can suggest placeholder users during submission, and they show up in the UI. Placeholders would be completely pointless if we didn't show them on maps!

**Comment by Gocnak** [comment]
Oh whoops, I thought there was just a typo, my bad. I understand what you mean now.
