### ISSUE TITLE
Review comment images downloading rather than opening in new window

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/website#983]
I know there's some fix for this just don't remember what :)

**Comment by GordiNoki** [comment]
If you just want to open images in new page you need `target="_blank"`, which we have, and images returning from cdn should have proper `image/png` content type. Currently they are `application/octet-stream`

**Comment by tsa96** [comment]
Yeah it's just us not setting a ContentType property in the S3 PutObjectCommand call

**Comment by tsa96** [comment]
Closed by #999, though my WIP code makes this use my new gallery component anyway.
